[exec]
topic = "c8y/devicecontrol/notifications"
on_fragment = "c8y_Command"
# FIXME: Remove once calling a workflow directly is supported. https://github.com/thin-edge/thin-edge.io/issues/3095
command = "create_workflow_command.sh --id ${.payload.id} --external-id ${.payload.externalSource.externalId} --command ${.payload.c8y_Command.text}"

skip_status_update = false
